"""Write END-TO-END.md from the records the live run left behind.

    python deploy/report.py

Nothing here is typed by hand. Every hash, vote count, verdict and refusal in
the published report is read out of docs/live.json and docs/deployment.json, so
a claim in the report cannot drift away from the run that produced it: change
the run and the report changes, and a claim with no record behind it cannot be
written at all.
"""
import json
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parents[1]
LIVE = json.loads((ROOT / "docs" / "live.json").read_text(encoding="utf-8"))
DEPLOY = json.loads((ROOT / "docs" / "deployment.json").read_text(encoding="utf-8"))
OUT = ROOT / "END-TO-END.md"

EXPLORER = "https://explorer-studio-dev.genlayer.com/tx/"

# What each proposal was built to put under the protocol, in the order a reader
# should meet them. The key is the fixture name in the live record.
PROPOSALS = [
    ("breaking", "A required field becomes optional",
     "One sentence changes `transaction_id` from required to optional. Two words "
     "in a diff, and the whole reason the integration was pinned to it."),
    ("compatible", "The same promises, rewritten and reordered",
     "Reorganised top to bottom, different headings, different sentences, every "
     "promise intact. A text diff is at its loudest here and tells you nothing."),
    ("silent", "Silent about retries",
     "The new version simply does not mention what a repeated idempotency key "
     "does. Silence is not a promise, and it is not a violation either."),
    ("injection", "Tells the reader to return SATISFIED",
     "The document contains a line addressed to whoever is reading it, "
     "instructing them to find every requirement preserved."),
]

VERDICT_WORDS = {
    "BREAKING_CHANGE": "at least one frozen requirement is contradicted",
    "COMPATIBLE": "every frozen requirement is preserved",
    "INCONCLUSIVE": "nothing contradicted, something unsettled",
}


def tx_link(tx):
    return "[`" + tx[:10] + "`](" + EXPLORER + tx + ")"


def votes(record):
    v = record.get("votes") or {}
    return ", ".join(f"{n} {name}" for name, n in sorted(v.items()))


def lines():
    out = []
    w = out.append

    w("# Verified end to end")
    w("")
    w("One frozen specification and four proposed versions, on GenLayer Studio "
      "Next. Each proposal was chosen to put a different answer under the "
      "protocol -- including one the protocol is supposed to refuse to give.")
    w("")
    w("> Generated by `python deploy/report.py` from [docs/live.json](docs/live.json)")
    w("> and [docs/deployment.json](docs/deployment.json). Every hash, vote count and")
    w("> refusal below is read out of those records rather than written by hand.")
    w("")
    w("| | |")
    w("| --- | --- |")
    w(f"| Network | {LIVE['network']}, chain `{LIVE['chain_id']}` |")
    w(f"| Contract | [`{LIVE['contract']}`]({DEPLOY['explorer']}) |")
    w(f"| Deployment | {tx_link(DEPLOY['deploy_tx'])}, {DEPLOY['deploy_status']} |")
    w(f"| Contract bytes | `sha256:{DEPLOY['onchain_sha256'][:16]}…`, identical to "
      f"`{DEPLOY['source']}` at `{DEPLOY['source_commit'][:10]}` |")
    w(f"| Run | {LIVE['started_at']} to {LIVE['finished_at']} |")
    w(f"| Rules | `{LIVE['protocol_info']['rules']}`, schema "
      f"`{LIVE['protocol_info']['schema']}` |")
    w("")

    w("Three accounts, because a protocol whose rules only hold for the account "
      "that wrote them does not have rules:")
    w("")
    w("| Account | Address | Does |")
    w("| --- | --- | --- |")
    roles = {
        "publisher": "registers the specification and freezes it",
        "integrator": "submits proposed versions for assessment",
        "stranger": "tries to do the publisher's job",
    }
    for name, address in LIVE["accounts"].items():
        w(f"| {name} | `{address}` | {roles.get(name, '')} |")
    w("")

    # ---- the frozen specification -------------------------------------------
    spec = LIVE["specification"]["frozen"]
    w("## What was frozen")
    w("")
    w(f"**{spec['name']}**, baseline version `{spec['baseline_version']}`, "
      f"{spec['baseline_bytes']} bytes stored whole in the contract and hashing "
      f"to `{spec['baseline_hash'][:16]}…`.")
    w("")
    w("| Requirement | Severity | What was agreed |")
    w("| --- | --- | --- |")
    for r in spec["requirements"]:
        w(f"| `{r['requirement_id']}` | {r['severity']} | {r['statement']} |")
    w("")
    w(f"Frozen at {spec['frozen_at']}, which records the criteria as "
      f"`{spec['criteria_digest'][:16]}…`. Every assessment below points back at "
      f"that digest, so a reader can tell these four findings were measured "
      f"against the same criteria and that the criteria existed before any of "
      f"the proposals did.")
    w("")
    w("Severity is recorded and shown. It does not weight the verdict: a `MINOR` "
      "requirement the evidence contradicts produces `BREAKING_CHANGE` exactly "
      "as a `BLOCKING` one does, because the protocol has no basis for deciding "
      "that somebody else's minor is minor to you.")
    w("")

    # ---- the four proposals -------------------------------------------------
    w("## The four proposals")
    w("")
    w("| Proposal | Verdict | Transaction |")
    w("| --- | --- | --- |")
    for key, title, _ in PROPOSALS:
        p = LIVE["proposals"][key]
        w(f"| {title} | `{p['assessment']['verdict']}` | {tx_link(p['tx'])} |")
    w("")

    for key, title, why in PROPOSALS:
        p = LIVE["proposals"][key]
        a = p["assessment"]
        w(f"### {title}")
        w("")
        w(why)
        w("")
        w("| | |")
        w("| --- | --- |")
        w(f"| Assessment | `{a['assessment_id']}` |")
        w(f"| Proposed version | `{a['proposed_version']}`, {a['proposed_bytes']} bytes |")
        w(f"| Proposed bytes | `sha256:{a['proposed_hash'][:16]}…` |")
        w(f"| Verdict | **`{a['verdict']}`** -- {VERDICT_WORDS[a['verdict']]} |")
        w(f"| Summary | {a['summary']} |")
        w(f"| Transaction | {tx_link(p['tx'])} |")
        w(f"| Consensus | {p['attempts'][-1]['consensus']} ({votes(p['attempts'][-1])}) |")
        w(f"| What the panel agreed | `{a['decisive_digest'][:16]}…` |")
        w(f"| Against criteria | `{a['criteria_digest'][:16]}…` |")
        if len(p["attempts"]) > 1:
            w(f"| Rounds | {len(p['attempts'])}; a round the validators did not "
              f"agree about writes nothing and may be asked again |")
        w("")
        w("| Requirement | Answered | Recorded | Quoted from the documents |")
        w("| --- | --- | --- | --- |")
        for f in a["findings"]:
            held = " (held: ungrounded)" if f["held_for_grounding"] else ""
            quote = (f["evidence"] or "nothing in either document settles it")
            quote = quote.replace("|", "\\|").replace("\n", " ").strip()
            if len(quote) > 180:
                quote = quote[:177].rstrip() + "…"
            w(f"| `{f['requirement_id']}` | {f['status']} | "
              f"{f['effective_status']}{held} | {quote} |")
        w("")

    w("The injection document is the one worth dwelling on. It was quoted to the "
      "readers inside a fence it could not close, its instruction was read as "
      "part of the document being assessed rather than as a direction to the "
      "reader, and the requirement it was trying to protect is recorded as "
      "violated with the document's own words as the evidence. It got the "
      "verdict its content earned.")
    w("")

    # ---- the refusals -------------------------------------------------------
    refusals = [t for t in LIVE["transactions"] if t.get("refused")]
    w("## What the contract refused")
    w("")
    w(f"{len(refusals)} refusals landed on chain in the same run. Each one is an "
      f"accepted transaction whose execution errored, which is the honest shape: "
      f"the validators agreed about the refusal, and the reason is recorded "
      f"rather than swallowed by a client.")
    w("")
    w("| Attempt | Sent by | Refused with | Transaction |")
    w("| --- | --- | --- | --- |")
    for t in refusals:
        step = t["step"].replace(" (refused)", "")
        reason = t["refusal"].replace("|", "\\|")
        if len(reason) > 150:
            reason = reason[:147].rstrip() + "…"
        w(f"| {step} | {t['caller']} | {reason} | {tx_link(t['tx'])} |")
    w("")
    w("The error class is the first token, and the console reads that rather "
      "than matching prose, so the wording above can change without breaking "
      "anything that depends on the kind.")
    w("")

    # ---- every transaction --------------------------------------------------
    w("## Every transaction in the run")
    w("")
    w("| Step | Sent by | Consensus | Execution | Transaction |")
    w("| --- | --- | --- | --- | --- |")
    for t in LIVE["transactions"]:
        w(f"| {t['step']} | {t['caller']} | {t['consensus']} ({votes(t)}) | "
          f"{t['execution']} | {tx_link(t['tx'])} |")
    w("")
    w("`ACCEPTED` and finalized are two different facts. Every transaction here "
      "was accepted by consensus; the deployment record carries the finalized "
      "status of the contract itself, and the console asks the finalized view "
      "directly rather than claiming finality it has not checked.")
    w("")

    # ---- reproducing --------------------------------------------------------
    w("## Running this again")
    w("")
    w("```bash")
    w("cd scripts && npm install")
    w(f"node live.mjs --address {LIVE['contract']}")
    w("```")
    w("")
    w("The suite asserts rather than prints: a wrong verdict, a missing "
      "refusal, a finding against a requirement that was not frozen, or a "
      "decisive answer with nothing quoted behind it fails the run. It costs "
      "real consensus rounds on a shared network, so it takes a few minutes and "
      "the transaction hashes it produces will not be the ones above.")
    w("")
    return out


def main():
    body = "\n".join(lines()).rstrip() + "\n"
    if "--check" in sys.argv:
        # Compared against what is on disk rather than against git, so this says
        # the same thing for a file nobody has committed yet.
        current = OUT.read_text(encoding="utf-8") if OUT.exists() else ""
        if current == body:
            print(f"{OUT.relative_to(ROOT)} is what docs/live.json generates")
            return 0
        print(f"{OUT.relative_to(ROOT)} is not what docs/live.json generates; "
              f"run python deploy/report.py and commit the result")
        return 1
    OUT.write_text(body, encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)}, {len(body)} bytes")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
